### ISSUE TITLE
error installing in R 4.2.2 BC 3.16

### ISSUE THREAD

**Issue by pelacables** [lmweber/WeberDivechaLCdata#1]
Hello,

I'm trying to install the package in R 4.2.2 and Bioconductor 3.16 and I get an error like this:
```
Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'WeberDivechaLCdata'
trying URL 'https://bioconductor.org/packages/3.16/data/experiment/src/contrib/WeberDivechaLCdata_1.0.1.tar.gz'
Content type 'application/gzip' length 228679 bytes (223 KB)
==================================================
downloaded 223 KB

* installing *source* package ‘WeberDivechaLCdata’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘WeberDivechaLCdata’
    finding HTML links ... done
    WeberDivechaLCdata                      html
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘WeberDivechaLCdata’:
 .onLoad failed in loadNamespace() for 'WeberDivechaLCdata', details:
  call: (function (cond)
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/BiocLibrary/3.16-foss-2021a-R-4.2.2/site-library/WeberDivechaLCdata’
```

I'm not a R expert (just a poor sysadmin) and google did not help with this error.
The only bug that sound a bit related is this one https://support.bioconductor.org/p/132864/ but even after setting the PROXY for the ExperimentHub did not help.

could you please help me?

**Comment by lcolladotor** [comment]
Hm.... from https://github.com/LieberInstitute/recount3/issues/39, maybe your issue is related to https://github.com/Bioconductor/BiocFileCache/pull/50

**Comment by lcolladotor** [comment]
Note that the fix in https://github.com/Bioconductor/BiocFileCache/pull/50 was implemented only in Bioc release (3.18) and devel (3.19), and you are using an older (and not fixed) version of Bioc (3.16). In short, you might want to upgrade to R 4.3.1 and use Bioc release (3.18).

**Comment by pelacables** [comment]
ok, so it means that I cannot install the package in 4.2,2 and BC 3,16, right?

**Comment by lcolladotor** [comment]
It can work in that version of Bioconductor, but you'll have to downgrade a few CRAN package versions. It's simplest to upgrade to BioC 3.18 with R 4.3.1

**Comment by pelacables** [comment]
Ok, thanks for your answer. I guess I close it now.
